"""How much is a domain-specific prompt worth? (upper bound for any context -> prompt generator)

The trained model is frozen (ViT, LoRA, LLM, Q-Former); only the visual prompt itself
(num_layers x num_vpt_tokens x hidden) is optimized with the training triplet loss on the
target domain's candidate pool (train split). Retrieval is evaluated on the disjoint
query/gallery identities, so this measures within-domain generalization of a tuned prompt.

Conditions per target domain / split:
  zero        all-zero prompt
  vicp        prompt generated by VICP from a random k=16 context (reference)
  opt_k<k>    prompt tuned from `vicp` on k random identities, one cross-camera pair each
              (same annotation as the in-context setting)
  opt_all     prompt tuned on every image of every pool identity (oracle)
  cross       opt_all prompt of domain A evaluated on domain B (is the gain domain-specific?)

Also measures where context information is lost: cosine similarity of the LLM hidden
states fed into prompt_mlp (h) vs. the resulting prompts, within / across domains.

Example:
  python scripts/oracle_prompt.py --output_dir experiments/oracle_prompt \
      --checkpoint experiments/cv_fold1_3k/val_cuhk03/checkpoint-3000 \
      --domains viper,grid,ilids --eval_splits 3 --opt_ks 4,16 --steps 300 --lr 1e-3 \
      --num_icl_samples 64 --fp16 False --report_to none
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))  # project root

import csv
import json
import time
from collections import defaultdict
from dataclasses import dataclass, field

import numpy as np
import torch
import torch.nn.functional as F
import transformers

from adapters.args_reid import ReIDTrainingArguments
from adapters.config_reid import DOMAIN_CONFIG, NUM_SPLITS

from adapters.trainer_reid import _get_dataset_cls, _seed_all
from scripts.context_sensitivity import build_model, SplitCache, evaluate, context_prompts, budget_ok


@dataclass
class OracleArguments:
    checkpoint: str = field(default="")
    domains: str = field(default="viper,grid,ilids")
    vicp_k: int = field(default=16)          # context size for the reference VICP prompt
    opt_ks: str = field(default="4,16")      # budgets for prompt tuning on k annotated identities
    steps: int = field(default=300)
    lr: float = field(default=1e-3)
    ids_per_batch: int = field(default=32)
    n_hcos_contexts: int = field(default=4)  # random contexts per domain for the h / prompt cosine check
    base_seed: int = field(default=0)


# ----------------------------------------------------------------------------- augmentation (GPU)

def augment(x, gen):
    """Flip, +-10 px translation (pad+crop), random erasing -- the tensor analogue of TRAIN_TRANSFORM
    minus colour jitter. x: (B, 3, H, W), already normalized."""
    B, _, H, W = x.shape
    flip = torch.rand(B, generator=gen, device=x.device) < 0.5
    x = torch.where(flip[:, None, None, None], torch.flip(x, dims=(3,)), x)
    xp = F.pad(x, (10, 10, 10, 10))
    out = torch.empty_like(x)
    dy = torch.randint(0, 21, (B,), generator=gen, device=x.device).tolist()
    dx = torch.randint(0, 21, (B,), generator=gen, device=x.device).tolist()
    for i in range(B):
        out[i] = xp[i, :, dy[i]:dy[i] + H, dx[i]:dx[i] + W]
    for i in range(B):  # RandomErasing(p=0.5, scale=(0.02, 0.4), ratio=(0.3, 3.3)), fill 0
        if torch.rand(1, generator=gen, device=x.device).item() >= 0.5:
            continue
        for _ in range(10):
            area = H * W * (0.02 + 0.38 * torch.rand(1, generator=gen, device=x.device).item())
            logr = np.log(0.3) + (np.log(3.3) - np.log(0.3)) * torch.rand(1, generator=gen, device=x.device).item()
            h, w = int(round((area * np.exp(logr)) ** 0.5)), int(round((area / np.exp(logr)) ** 0.5))
            if h < H and w < W:
                y0 = torch.randint(0, H - h + 1, (1,), generator=gen, device=x.device).item()
                x0 = torch.randint(0, W - w + 1, (1,), generator=gen, device=x.device).item()
                out[i, :, y0:y0 + h, x0:x0 + w] = 0
                break
    return out


# ----------------------------------------------------------------------------- prompt tuning

def tune_prompt(model, cache, id2imgs, init, steps, lr, ids_per_batch, seed):
    """Optimize only the prompt tensor with the training triplet loss. id2imgs: list of index lists
    into cache.pool_imgs, one list per identity (>= 2 images, or a single pair)."""
    device = cache.pool_imgs.device
    gen = torch.Generator(device=device).manual_seed(seed)
    rng = np.random.RandomState(seed)
    prompt = torch.nn.Parameter(init.detach().clone().float())
    opt = torch.optim.Adam([prompt], lr=lr)
    P = min(ids_per_batch, len(id2imgs))
    losses = []
    with torch.enable_grad():
        for step in range(steps):
            ids = rng.choice(len(id2imgs), size=P, replace=False)
            idx, labels = [], []
            for j, i in enumerate(ids):
                a, b = rng.choice(id2imgs[i], size=2, replace=len(id2imgs[i]) < 2)
                idx += [a, b]
                labels += [j, j]
            x = augment(cache.pool_imgs[torch.tensor(idx, device=device)], gen)
            feats = model(x, prompts=prompt)["features"]
            loss = model.loss(feats, torch.tensor(labels, device=device))
            opt.zero_grad(set_to_none=True)
            loss.backward()
            opt.step()
            losses.append(loss.item())
    return prompt.detach(), float(np.mean(losses[:20])), float(np.mean(losses[-20:]))


def pool_id2imgs(cache, pids=None, pairs=None):
    """All pool images per identity (pids) or exactly the annotated pairs."""
    if pairs is not None:
        return [[cache.pool_idx[a], cache.pool_idx[b]] for a, b in pairs]
    out = []
    for pid in (pids if pids is not None else cache.pool.eligible_pids):
        out.append([cache.pool_idx[p] for p, _ in cache.pool.pid2items[pid]])
    return out


# ----------------------------------------------------------------------------- h vs prompt cosine

class _MLPInput:
    """Captures the input of prompt_mlp (LLM hidden states at the query-token positions)."""

    def __init__(self, module):
        self.h = None
        module.register_forward_hook(self._hook)

    def _hook(self, module, inp, out):
        self.h = inp[0].detach().float()


def mean_token_cos(a, b):
    """a, b: (tokens, dim). Mean over tokens of the cosine between matching tokens."""
    return F.cosine_similarity(a, b, dim=-1).mean().item()


def main():
    parser = transformers.HfArgumentParser((ReIDTrainingArguments, OracleArguments))
    args, oargs = parser.parse_args_into_dataclasses()
    device = "cuda"
    torch.backends.cuda.matmul.allow_tf32 = True
    torch.backends.cudnn.allow_tf32 = True
    model = build_model(args, device, oargs.checkpoint)
    state = torch.load(os.path.join(oargs.checkpoint, "pytorch_model.bin"), map_location=device, weights_only=True)
    missing, unexpected = model.load_state_dict(state, strict=False)
    print("checkpoint:", oargs.checkpoint, "missing:", len(missing), "unexpected:", len(unexpected))
    for p in model.parameters():
        p.requires_grad_(False)
    mlp_in = _MLPInput(model.prompt_mlp)

    domains = oargs.domains.split(",")
    opt_ks = [int(k) for k in oargs.opt_ks.split(",") if k]
    L, V = model.num_layers, args.num_vpt_tokens
    zero = torch.zeros(1, L, V, model.hidden_size, device=device)
    os.makedirs(args.output_dir, exist_ok=True)
    rows, t0 = [], time.time()
    hs = defaultdict(list)       # domain -> [(h, prompt)] from split 0
    oracle = defaultdict(dict)   # split -> domain -> opt_all prompt
    caches = {}

    def add(**r):
        rows.append(r)
        print("[{:6.0f}s] {}".format(time.time() - t0, " ".join("{}={}".format(k, round(v, 2) if isinstance(v, float) else v)
                                                              for k, v in r.items())), flush=True)

    for name in domains:
        n_splits = min(args.eval_splits, NUM_SPLITS.get(name, 1))
        for split_id in range(n_splits):
            kwargs = {"split_id": split_id} if name in NUM_SPLITS else {}
            try:
                ds = _get_dataset_cls(name)(root=DOMAIN_CONFIG["data_root"], verbose=False, **kwargs)
            except Exception as e:
                print("Skipping {} split {}: {}".format(name, split_id, e))
                break
            assert not ({p for p, *_ in ds.train} & {p for p, *_ in ds.query + ds.gallery}), "leak"
            cache = SplitCache(ds, device, name)
            caches[(name, split_id)] = cache
            s = oargs.base_seed + 1000 * split_id
            base = dict(domain=name, split=split_id, train_domain=name)

            r1, mAP = evaluate(model, cache, zero, s)
            add(**base, condition="zero", k=0, rank1=r1, mAP=mAP)

            # reference VICP prompt (random k context), same RNG convention as run_eval
            rng = np.random.RandomState(s)
            pairs, _ = cache.sampler.draw(args.selection_unit, "random", oargs.vicp_k, rng)
            vicp = context_prompts(model, cache, pairs, s)
            r1, mAP = evaluate(model, cache, vicp, s)
            add(**base, condition="vicp", k=oargs.vicp_k, rank1=r1, mAP=mAP)

            if split_id == 0:  # h / prompt for the cosine analysis
                for c in range(oargs.n_hcos_contexts):
                    rc = np.random.RandomState(s + 1 + c)
                    pc, _ = cache.sampler.draw(args.selection_unit, "random", oargs.vicp_k, rc)
                    pr = context_prompts(model, cache, pc, s + 1 + c)
                    hs[name].append((mlp_in.h[0], pr[0].reshape(L * V, -1).float()))

            for k in opt_ks:
                if not budget_ok(cache, args.selection_unit, k):
                    continue
                rng = np.random.RandomState(s + 7)
                pk, _ = cache.sampler.draw(args.selection_unit, "random", k, rng)
                pr, l0, l1 = tune_prompt(model, cache, pool_id2imgs(cache, pairs=pk), vicp, oargs.steps, oargs.lr,
                                         oargs.ids_per_batch, s + 7)
                r1, mAP = evaluate(model, cache, pr, s)
                add(**base, condition="opt_k{}".format(k), k=k, rank1=r1, mAP=mAP, loss_start=l0, loss_end=l1,
                    delta_norm=(pr - vicp).norm().item() / vicp.norm().item())

            pr, l0, l1 = tune_prompt(model, cache, pool_id2imgs(cache), vicp, oargs.steps, oargs.lr,
                                     oargs.ids_per_batch, s + 11)
            oracle[split_id][name] = pr
            r1, mAP = evaluate(model, cache, pr, s)
            add(**base, condition="opt_all", k=len(cache.pool), rank1=r1, mAP=mAP, loss_start=l0, loss_end=l1,
                delta_norm=(pr - vicp).norm().item() / vicp.norm().item())

    # cross-domain: prompt tuned on domain A, evaluated on domain B (same split id)
    for split_id, by_dom in oracle.items():
        for src, pr in by_dom.items():
            for dst in by_dom:
                if dst == src:
                    continue
                r1, mAP = evaluate(model, caches[(dst, split_id)], pr, 1000 * split_id + oargs.base_seed)
                add(domain=dst, split=split_id, train_domain=src, condition="cross", k=0, rank1=r1, mAP=mAP)

    # where is context information lost? h (prompt_mlp input) vs prompt, within / across domains
    hcos = {}
    names = list(hs)
    for which, j in (("h", 0), ("prompt", 1)):
        within, across = [], []
        for a in range(len(names)):
            for b in range(a, len(names)):
                for i, x in enumerate(hs[names[a]]):
                    for jj, y in enumerate(hs[names[b]]):
                        if a == b and jj <= i:
                            continue
                        (within if a == b else across).append(mean_token_cos(x[j], y[j]))
        hcos[which] = dict(within=float(np.mean(within)) if within else None,
                           across=float(np.mean(across)) if across else None)
    # spread of h across contexts relative to its magnitude
    allh = torch.stack([x[0] for n in names for x in hs[n]])
    allp = torch.stack([x[1] for n in names for x in hs[n]])
    hcos["h_rel_std"] = (allh.std(0).norm() / allh.mean(0).norm()).item()
    hcos["prompt_rel_std"] = (allp.std(0).norm() / allp.mean(0).norm()).item()
    print("h / prompt cosine:", json.dumps(hcos, indent=1))
    with open(os.path.join(args.output_dir, "h_prompt_cosine.json"), "w") as f:
        json.dump(hcos, f, indent=1)

    keys = ["domain", "split", "train_domain", "condition", "k", "rank1", "mAP", "loss_start", "loss_end", "delta_norm"]
    with open(os.path.join(args.output_dir, "oracle_prompt.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        w.writerows(rows)

    # summary: mean over splits
    print("\n{:8s} {:8s} {:10s} {:>7s} {:>7s}".format("domain", "from", "condition", "rank1", "mAP"))
    agg = defaultdict(list)
    for r in rows:
        agg[(r["domain"], r["train_domain"], r["condition"])].append((r["rank1"], r["mAP"]))
    for (d, src, c), v in sorted(agg.items()):
        m = np.mean(v, axis=0)
        print("{:8s} {:8s} {:10s} {:7.2f} {:7.2f}  (n={})".format(d, src, c, m[0], m[1], len(v)))
    print("total time: {:.0f}s".format(time.time() - t0))


if __name__ == "__main__":
    main()
